"""This module contains the images used in FixCat.

They are encoded in this module so we don't have
to ship dedicated imaged files.

You can encode a existing image with the img2py
utility shipped with wxPython. After that add it
to this file and use it in the application."""

#----------------------------------------------------------------------
# This file was generated by /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/tools/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

n_frame = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAA8AAAASCAYAAACEnoQPAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAAN1wAADdcBQiibeAAAAAd0SU1FB9wBHxIUEymA+RgAAAGw"
    "SURBVDjLldSxaxRBGMbhZ3Y33iGk0CI2C5YpbEQUSWEVsBS7/Ak22kgqGxFRJFiaRuwMQkAC"
    "NsLZ5VqbIMohgnASuAieZ47D88TdsXBXwqHhMjBMM79532++dyZFC9/wwezjJN7DV0Q8wVnM"
    "zQh/gl4FR3zEDeSzwp8rsKzWn3iByzh+GJwhgfn5eQsLCzFJkrk0Ta+MRqNzu7u7z/EMr/9n"
    "4UuapnFlZaVst9txa2urbLVacXV1tXbzFjeR/Us5pGkqz/PQ7/etra2ZTCZxMBhAwBncxyXc"
    "wQ4K1WkJlGVpf38/djqdMBwOY4yxVolo4GrVjUd4iZAgxBglSWJ5eTmsr6/Hzc3NsLS0FA7Y"
    "rLtxGg9xD42/yjFG3W7X9va2oijs7e2ZgkM1X+ExLmQIIfwR6XQ6cWNjI4zH49pzrZ6gX0EP"
    "qprLpN4QQtBoNEKz2YxT3Qh4g2u4hSGaCBmSGKPBYBB7vV4oiuKg4qjK/m28myoDjEMIMc/z"
    "cnFxscyyrL6cnSqqJw6L54+peE7wFOdnyfbkQCt6uI5Tsz6MXxXYxsWjPsnvuItjR/wMur8B"
    "8+2raIjpbfYAAAAASUVORK5CYII=")
getn_frameData = n_frame.GetData
getn_frameImage = n_frame.GetImage
getn_frameBitmap = n_frame.GetBitmap

#----------------------------------------------------------------------
next_uncat = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACQAAAASCAYAAAAzI3woAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAAN1wAADdcBQiibeAAAAAd0SU1FB9wBHxIVAcMiuREAAAH7"
    "SURBVEjHzdVNiM1RGAbw371jhtGMbyVKkzRDZCUWLCwU+SgWysfCysJGlrMQTXaSssDKx85a"
    "YmGBFCkLmimMUTQo+ZhS4jbdO3+b91+nv3tNd1wfT51OnTrv+5z3ed73lDSHNnRhKbZgO1Zh"
    "Lip4iRuxRvAFVWRajA704TDuRYLJ1igGsAGzWklmEQ7hfiHhBL7hM97jI76iVofYaaxFexK3"
    "HcuxAp35YWkSMutxBDvRHWcZXmEwZHkTRKZjCZZFkpVpIjzBBVzFNOzGgbh3CjdD3obYgUeF"
    "176LoFuxOIKVk8d1YB7WoR8PC/c/4VxU7ENyfgXzf0VmF54Wgt0KE3c30QBrIvnbRMpqSJ3L"
    "nuEBehsF2lYgU8P56KypoBzVGg8CxZXhddjjJ2wKrXMy33Gs4IVmUMJBDDUgkxMax95EfsKE"
    "dxIyFRwtdEazlTkesyhrQKaWkOoPs4M5OFvwzECYdKroS0ydJi9WJ98v5kqUsT/kyclcDpK/"
    "gxk4ibHEi7U65HKzP8NC4e7hhMztkK8V6Iw59ryOTPWq1QMnEjIj0WWtxkZcD19mDbyUYXNb"
    "HCyIgXYphtREiwmNxtdTCW91RQdmsedrLL/Qg30x9v8kZmIP7iZVSSUbLrbp30AZq3EmGQm5"
    "r6r+IWbHMHyRfCmZ/wC9uBYVevwDgHrPa+kodJ4AAAAASUVORK5CYII=")
getnext_uncatData = next_uncat.GetData
getnext_uncatImage = next_uncat.GetImage
getnext_uncatBitmap = next_uncat.GetBitmap

#----------------------------------------------------------------------
pause = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAA0AAAASCAYAAACAa1QyAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAAN1wAADdcBQiibeAAAAAd0SU1FB9wBHxIUHc441B8AAABQ"
    "SURBVCjP7c4xCoBAEEPR5wiWHtLbeTZPYCFrocW4bKGlsB8CQ0iYwI6StGFxMWPFkTOBKRkw"
    "IO57vPUgUrBFaZlRfXhFfAnX83qpl35ROgG2Eg4l8glK0wAAAABJRU5ErkJggg==")
getpauseData = pause.GetData
getpauseImage = pause.GetImage
getpauseBitmap = pause.GetBitmap

#----------------------------------------------------------------------
p_frame = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAA8AAAASCAYAAACEnoQPAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAAN1wAADdcBQiibeAAAAAd0SU1FB9wBHxIUJn8zPTsAAAGk"
    "SURBVDjLndSxa1NRFMfxz3197xl0KFFCQEpxdurSIf+AILg66CaIOGhnEYqLc/sHKJ0cRRyl"
    "o2KnlkYs7ebgYAgEEkRe1JfkurzAE0pNvXA5XLjfc879nXMufMVli6+AW3jnHHCGNbxExHBR"
    "eAWP8KUCI779C76IG3iL3xU0q2w/PSPaOu40Go3bnU5npd1uW1paijFGu7u7BoNBchqcYgP3"
    "cL3ZbCabm5vKsozD4TBkWRYPDg4MBoMwh6eVXcMz3MQFyPM8lmVpa2tLt9uV53no9/sQ0kr6"
    "q7hfiXKtchQRYoxijGazWZhOp3E8HofJZAIJ9PGmJkZ9x9XV1XhychIPDw9ne3t7cXt7O7Za"
    "rYhRihIvcKlSdl6KMBeh1+vZ2dlxfHxsPB4bjUaQpNV73+MjnuABrlQOhBBiURSOjo5Ct9ut"
    "Ow1JdWjgO57iIT7XI2dZJs/zv7JBktTEma/XuFvp8KMoirC/vx+qVOt3w1kd1sRGkiSflpeX"
    "Y5qmdUEjxov09jpendKePxcdjDYeo1erxq/zjmQHHyp44j8+gxzPUfwBjZywoyzhouAAAAAA"
    "SUVORK5CYII=")
getp_frameData = p_frame.GetData
getp_frameImage = p_frame.GetImage
getp_frameBitmap = p_frame.GetBitmap

#----------------------------------------------------------------------
play = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAA4AAAASCAYAAABrXO8xAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAAN1wAADdcBQiibeAAAAAd0SU1FB9wBHxIUMfzguPwAAADr"
    "SURBVDjLldO9SgNBFIbhB0SsRasUlkERey9AiBdha5nOTrD2Cuy8AbuUIqSysBQ7K0FIE5Mo"
    "waCJmrXZhWGY1dlpDvPznu+cmW9WcIsRHjUcIxToYRdrueCwBAsMcILtHPClhJZlXOABh2jl"
    "lLoM4AJjXOGgDhxHYJzgGadYj8FJcKguwRfu0AnB1wiKY5hghkvswFtCMaX+E+z1YJoBhaoX"
    "2IL3mvLiKp5wHPY4q1Gp1r5xg734Vj8SYDWf4gybqXf8TEBz9HH0l3PmUY8TdNH+z6uLoLTr"
    "0mKrOSavoHNsNPmP99hv+ol/AcfmhBb91fsDAAAAAElFTkSuQmCC")
getplayData = play.GetData
getplayImage = play.GetImage
getplayBitmap = play.GetBitmap
